version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: yupichat-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: yupichat_admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-SecureYupiPassword123!}
      MONGO_INITDB_DATABASE: yupichat
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - yupichat-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optionnel: MongoDB Express pour l'administration (seulement en dev)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: yupichat-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: yupichat_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-SecureYupiPassword123!}
      ME_CONFIG_MONGODB_URL: mongodb://yupichat_admin:${MONGO_PASSWORD:-SecureYupiPassword123!}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-AdminYupi123!}
    depends_on:
      - mongodb
    networks:
      - yupichat-network
    profiles:
      - development # Seulement en mode développement

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  yupichat-network:
    driver: bridge
