module.exports = {
  apps: [
    {
      name: "no-skills-chat",
      script: "./server/server-simple.js",
      instances: "max",
      exec_mode: "cluster",
      env: {
        NODE_ENV: "development",
        PORT: 3001,
        DB_HOST: "localhost",
        DB_PORT: 5432,
        DB_NAME: "no_skills_chat",
        DB_USER: "postgres",
        DB_PASSWORD: "password",
        JWT_SECRET: "no-skills-super-secret-key-2025",
        EMAIL_HOST: "smtp.gmail.com",
        EMAIL_PORT: 587,
        EMAIL_USER: "noreply@no-skills.fr",
        EMAIL_PASS: "your-email-password",
        UPLOAD_PATH: "./uploads",
        MAX_FILE_SIZE: "10mb",
        CORS_ORIGIN: "http://localhost:3000",
        ADMIN_USERNAME: "Yupi",
        ADMIN_PASSWORD: "1515Dh!dofly",
        ADMIN_EMAIL: "admin@no-skills.fr",
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 3001,
        DB_HOST: "localhost",
        DB_PORT: 5432,
        DB_NAME: "no_skills_chat_prod",
        DB_USER: "postgres",
        DB_PASSWORD: "production-password",
        JWT_SECRET: "production-super-secret-key-2025-very-long-and-secure",
        EMAIL_HOST: "smtp.no-skills.fr",
        EMAIL_PORT: 587,
        EMAIL_USER: "noreply@no-skills.fr",
        EMAIL_PASS: "production-email-password",
        UPLOAD_PATH: "/var/www/no-skills-chat/uploads",
        MAX_FILE_SIZE: "10mb",
        CORS_ORIGIN: "https://no-skills.fr",
        ADMIN_USERNAME: "Yupi",
        ADMIN_PASSWORD: "1515Dh!dofly",
        ADMIN_EMAIL: "admin@no-skills.fr",
      },
      log_file: "./logs/app.log",
      error_file: "./logs/error.log",
      out_file: "./logs/out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      max_memory_restart: "500M",
      node_args: "--max-old-space-size=1024",
      watch: false,
      ignore_watch: ["node_modules", "logs", "uploads"],
      max_restarts: 10,
      min_uptime: "10s",
      kill_timeout: 5000,
      restart_delay: 4000,
      autorestart: true,
      // Configuration pour Termius et déploiement
      deploy: {
        production: {
          user: "no-skills",
          host: "no-skills.fr",
          ref: "origin/main",
          repo: "git@github.com:your-username/no-skills-chat.git",
          path: "/var/www/no-skills-chat",
          "pre-deploy-local": "",
          "post-deploy":
            "npm install && npm run build && pm2 reload ecosystem.config.cjs --env production",
          "pre-setup": "",
        },
      },
    },
  ],
};
